<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PDF Generated by Ceylon Linux (PVT) LTD</title>
    <style>
        body {
            color: #101010
        }

        .center {
            text-align: center
        }

        .block {
            /* margin-left:auto; */
            width: 100%;
        }

        .search-terms {
            border: 1px solid #404040;
            width: 25%;
            margin-right: 1em;
            min-width: 300px
        }

        .search-terms strong {
            background: #404040;
            color: #fff;
            display: block
        }

        .tbl {
            margin: auto;
        }

        .tbl th {
            background: #404040;
            color: #fff;
        }

        .tbl td {
            border: solid #404040 1px;
        }

    </style>
</head>

<body>
    <div class="center">
        <a href="{{ url('/') }}">
            <img height=80 src="{{ url('/images/logo_expanded.png') }}" alt="Sunshine logo">
        </a>
        <h1>{{ config('app.name', 'Laravel') }}</h1>
        <h2>{{ $title }}</h2>
    </div>
    @if(!empty($searchTerms))
    <div class="block">
        <hr>
    </div>
    <table width="100%">
        <tbody>
            <tr>
                <td width="60%"></td>
                <td>
                    <div class="search-terms block">
                        <strong>Search Terms:-</strong>
                        @foreach( $searchTerms as $term )
                        <div>
                            <b>{{ $term['label'] }}</b> - {{ $term['value'] }}
                        </div>
                        @endForeach
                    </div>

                </td>
            </tr>
        </tbody>
    </table>
    @endIf
    <div class="tbl-wrapper">
        <hr>
        <table class="tbl">
            <thead>
                <tr>
                    @foreach( $columns as $columnName )
                    <th>{{ $columnName }}</th>
                    @endForeach
                    </th>
            </thead>
            <tbody>
                @foreach( $results as $result )
                <tr>
                    @foreach( $result as $data)
                    <td>{{ $data }}</td>
                    @endForeach
                </tr>
                @endForeach
            </tbody>
        </table>
        <hr>
    </div>
    <table width="100%">
        <tbody>
            <tr>
                <td width="60%"></td>
                <td>
                    <div class="search-terms block">
                        <strong>Info:-</strong>
                        <div> <b>Page:-</b> {{ $page }} </div>
                        <div> <b>Rows Per Page:-</b> {{ $per_page }} </div>
                        <div> <b>Sorted By :-</b> {{ $sorted_by }} </div>
                        <div> <b>Sorted Mode :-</b> {{ $sorted_mode }} </div>
                        <div> <b>Generated At :-</b> {{ date('Y-m-d H:i:s') }} </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <hr>
    Copyrighted by {{ date('Y') }} Ceylon Linux (PVT) LTD All Rights Reserved.
</body>

</html>
