<table>
    <thead>
        <tr>
            <th style="text-align:center" colspan="{{ count($columns) }}">
                <b>
                    {{ $title }}
                </b>
            </th>
        </tr>
        <tr>
            <th colspan="{{ count($columns) }}">

            </th>
        </tr>
        @if(count($searchTerms))
            <tr>
                <td style="text-align:center" colspan="4" >
                    <b>Searched Terms</b>
                </td>
                <td colspan="{{ count($columns) -4 }}">
                </td>
            </tr>
            @foreach ($searchTerms as $searchTerm)
                <tr>
                    <td colspan="2" >
                        {{$searchTerm['label']}} :-
                    </td>
                    <td colspan="2">
                        {{$searchTerm['value']}}
                    </td>
                    <td colspan="{{ count($columns) -4 }}">
                    
                    </td>
                </tr>
            @endforeach
        @endIf
        <tr>
            <th colspan="{{ count($columns) }}">

            </th>
        </tr>
        @if(isset($additionalHeaders))
            @foreach ($additionalHeaders as $additionalHeader)
                <tr>
                    @foreach ($additionalHeader as $headerCell)
                        <th style="background-color:#757575" colspan="{{  isset($headerCell['colSpan'])?$headerCell['colSpan']:1 }}" rowspan="{{ isset($headerCell['rowSpan'])?$headerCell['rowSpan']:1 }}" >
                            {{ $headerCell['title'] }}
                        </th>
                    @endforeach
                </tr>
            @endforeach
        @endIf
        <tr>
            @foreach ($columns as $column )
                <th align="left" style="background-color:#757575">
                    {{  $column->getLabel() }}
                </th>
            @endforeach
        </tr>
    </thead>
    <tbody>
       @foreach ($results as $result )
           <tr >
                @foreach ($columns as $columnName =>$column )
                    @if((isset($result[$columnName.'_rowspan'])&&$result[$columnName.'_rowspan']>0)||!isset($result[$columnName.'_rowspan']))
                        <td
                            valign="center"
                        style="@if(isset($result[$columnName.'_style']))
                            @foreach ($result[$columnName.'_style'] as $name => $value )
                                @if($name!='background')
                                    {{$name}}:{{$value}};
                                @endIf
                            @endforeach
                        @endIf
                        @if(isset($result['special']))
                                background: #90caf9;
                            @else
                                @if(isset($result[$columnName.'_style'])&&isset($result[$columnName.'_style']['background']))
                                    background: {{$result[$columnName.'_style']['background']}};
                            @endIf
                        @endIf
                        "
                        colspan="{{  isset($result[$columnName.'_colspan'])? $result[$columnName.'_colspan'] :1 }}" 
                        rowspan="{{  isset($result[$columnName.'_rowspan'])? $result[$columnName.'_rowspan'] :1 }}" >
                            {{ $column->render(isset($result[$columnName])?$result[$columnName]:null) }}
                        </td>
                    @endIf
                @endforeach
           </tr>
       @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td colspan="{{ count($columns) }}"></td>
        </tr>
        <tr>
            <td colspan="{{ count($columns) -4 }}">
            
            </td>
            <td colspan="2">
                Generated time:-
            </td>
            <td colspan="2">
                {{ $time }}
            </td>
        </tr>
        <tr>
            <td colspan="{{ count($columns) -4 }}">
            
            </td>
            <td colspan="2" >
                Generated by:-
            </td>
            <td colspan="2">
                {{ $user->name }} [ {{  $user->u_code }} ]
            </td>
        </tr>
        @if(isset($sorted_by))
            <tr>
                <td colspan="{{ count($columns) -4 }}">
                
                </td>
                <td colspan="2" >
                    Sorted By:-
                </td>
                <td colspan="2">
                    {{$sorted_by}}
                </td>
            </tr>
            <tr>
                <td colspan="{{ count($columns) -4 }}">
                
                </td>
                <td colspan="2" >
                    Sorted Mode:-
                </td>
                <td colspan="2">
                    {{$sorted_mode}}
                </td>
            </tr>
        @endIf
        <tr>
            <td colspan="{{ count($columns) }}"></td>
        </tr>
        <tr>
            <td colspan="{{ count($columns) }}" style="text-align: center;color:#ffffff; background:#000000">
                    © 2019 🐧 Ceylon Linux (PVT) LTD| All Rights Reserved.
            </td>
        </tr>
        <tr>
            <td colspan="{{ count($columns) }}">
                <a href="{{ $link }}">Download the original document.</a>
            </td>
        </tr>
    </tfoot>
</table>