// Main actions
export const USER_LOADING = 'USER_LOADING';
export const GUEST_ACCESS = 'GUEST_ACCESS';
export const USER_ACCESS = 'USER_ACCESS';
export const XHR_ERROR = 'XHR_ERROR';

// Login Form
export const LOGIN_USERNAME_CHANGE = 'LOGIN_USERNAME_CHANGE';
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE';
export const LOGIN_NEW_PASSWORD_CHANGE = 'LOGIN_NEW_PASSWORD_CHANGE';
export const LOGIN_REMEMBER_CHANGE = 'LOGIN_REMEMBER_CHANGE';
export const LOGIN_FORM_LOADING = 'LOGIN_FORM_LOADING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PASSWORD_EXPIRED = 'LOGIN_PASSWORD_EXPIRED';

//Layouts
export const SIDEBAR_LOADING = 'SIDEBAR_LOADING';
export const SIDEBAR_LOADED = 'SIDEBAR_LOADED';

// Header
export const HEADER_USER_MENU_TOGGLE = 'HEADER_USER_MENU_TOGGLE';

// Sidebar
export const SIDEBAR_CLICK_MAIN_ICON = 'SIDEBAR_CLICK_MAIN_ICON';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SIDEBAR_SECTION_COLLAPSE = 'SIDEBAR_SECTION_COLLAPSE';
export const SIDEBAR_SECTION_EXPAND = 'SIDEBAR_SECTION_EXPAND';
export const SIDEBAR_CHANGE = 'SIDEBAR_CHANGE';
export const SIDEBAR_MOBILE_TOGGLE = 'SIDEBAR_MOBILE_TOGGLE';

// CRUD page
export const CRUD_PAGE_LOADING = 'CRUD_PAGE_LOADING';
export const CRUD_PAGE_LOADED = 'CRUD_PAGE_LOADED';
export const CRUD_PAGE_FORM_VALUES_CHANGE = 'CRUD_PAGE_FORM_VALUES_CHANGE';
export const CRUD_PAGE_SEARCH_RESULTS_LOADING = 'CRUD_PAGE_SEARCH_RESULTS_LOADING';
export const CRUD_PAGE_SEARCH_RESULTS_LOADED = 'CRUD_PAGE_SEARCH_RESULTS_LOADED';
export const CRUD_PAGE_ORDER_BY_CHANGE = 'CRUD_PAGE_ORDER_BY_CHANGE';
export const CRUD_FORM_CLEAR = 'CRUD_FORM_CLEAR';
export const CRUD_CHOOSE_TO_UPDATE = 'CRUD_CHOOSE_TO_UPDATE';
export const CRUD_CHOOSE_TO_DELETE = 'CRUD_CHOOSE_TO_DELETE';
export const CRUD_CHOOSE_TO_RESTORE = 'CRUD_CHOOSE_TO_RESTORE';
export const CRUD_SEARCH_CLICK = 'CRUD_SEARCH_CLICK';
export const CRUD_CREATE_CLICK = 'CRUD_CREATE_CLICK';
export const CRUD_MODAL_CLOSE = 'CRUD_MODAL_CLOSE';
export const CRUD_CHANGE_PAGE_NUMBER = 'CRUD_CHANGE_PAGE_NUMBER';
export const CRUD_CHANGE_ROWS_COUNT = 'CRUD_CHANGE_ROWS_COUNT';
export const CRUD_CLEAR_DELETE = 'CRUD_CLEAR_DELETE';
export const CRUD_CLEAR_RESTORE = 'CRUD_CLEAR_RESTORE';

// CRUD Form
export const CRUD_SEARCH_TOGGLE = 'CRUD_SEARCH_TOGGLE';

// Dialogs and confirmations
export const DIALOG_ALERT = 'DIALOG_ALERT';
export const DIALOG_CONFIRMATION = 'DIALOG_CONFIRMATION';
export const DIALOG_CLOSE_SNACK = 'DIALOG_CLOSE_SNACK';

// Dashboard actions
export const DASHBOARD_LOADED = 'DASHBOARD_LOADED';

// Itinerary Page
export const ITINERARY_MR_CHANGE = 'ITINERARY_MR_CHANGE';
export const ITINERARY_FM_CHANGE = 'ITINERARY_FM_CHANGE';
export const ITINERARY_YEAR_MONTH_CHANGE = 'ITINERARY_YEAR_MONTH_CHANGE'
export const ITINERARY_LOADING = 'ITINERARY_LOADING';
export const ITINERARY_LOADED = 'ITINERARY_LOADED';
export const ITINERARY_NOT_SET = 'ITINERARY_NOT_SET';
export const ITINERARY_DATE_CHANGE = 'ITINERARY_DATE_CHANGE';
export const ITINERARY_DAY_TYPES_LOADED = 'ITINERARY_DAY_TYPES_LOADED';
export const ITINERARY_DATE_SELECTED = 'ITINERARY_DATE_SELECTED';
export const ITINERARY_DATE_CANCEL = 'ITINERARY_DATE_CANCEL';
export const ITINERARY_DAYS_LOADED = 'ITINERARY_DAYS_LOADED';
export const ITINERARY_CHANGE_ADDITIONAL_VALUES = 'ITINERARY_CHANGE_ADDITIONAL_VALUES';
export const ITINERARY_CONFIRM_ADDITIONAL_VALUES = 'ITINERARY_CONFIRM_ADDITIONAL_VALUES';
export const ITINERARY_CLEAR_DATE = 'ITINERARY_CLEAR_DATE';
export const ITINERARY_LOADED_FM_TEAM_MEMBERS = 'ITINERARY_LOADED_FM_TEAM_MEMBERS';
export const ITINERARY_CHANGE_JOIN_FIELD_WORKER = 'ITINERARY_CHANGE_JOIN_FIELD_WORKER';
export const ITINERARY_CHANGE_OTHER_DAY = 'ITINERARY_CHANGE_OTHER_DAY';
export const ITINERARY_CLEAR = 'ITINERARY_CLEAR';

// Doctor time table
export const DOC_TIME_TABLE_DOC_CHANGE = 'DOC_TIME_TABLE_DOC_CHANGE';
export const DOC_TIME_TABLE_MODAL_OPEN = 'DOC_TIME_TABLE_MODAL_OPEN'
export const DOC_TIME_TABLE_MODAL_CLOSE = 'DOC_TIME_TABLE_MODAL_CLOSE';
export const DOC_TIME_TABLE_NEW_VALUES_EDIT = 'DOC_TIME_TABLE_NEW_VALUES_EDIT';
export const DOC_TIME_TABLE_SHEDULES_CHANGE = 'DOC_TIME_TABLE_SHEDULES_CHANGE';

// Team Product Allocations page
export const TEAM_PROD_ALLOC_TEAM_CHANGE = 'TEAM_PROD_ALLOC_TEAM_CHANGE';
export const TEAM_PROD_ALLOC_DATA_LOADED = 'TEAM_PROD_ALLOC_DATA_LOADED';
export const TEAM_PROD_ALLOC_CHANGE_DATA = 'TEAM_PROD_ALLOC_CHANGE_DATA';

// Reports actions
export const REPORT_CLEAR_PAGE = 'REPORT_CLEAR_PAGE';
export const REPORT_CHANGE_REPORT = 'REPORT_CHANGE_REPORT';
export const REPORT_CHANGE_SEARCH_TERMS = 'REPORT_CHANGE_SEARCH_TERMS';
export const REPORT_RESULTS_LOADED = 'REPORT_RESULTS_LOADED';
export const REPORT_CHANGE_COLUMNS = 'REPORT_CHANGE_COLUMNS';

// GPS Tracking
export const GPS_USER_CHANGE = 'GPS_USER_CHANGE';
export const GPS_DATE_CHANGE = 'GPS_DATE_CHANGE';
export const GPS_DATA_LOADED = 'GPS_DATA_LOADED';
export const GPS_TIME_CHANGE = 'GPS_TIME_CHANGE';

// Standard Itinerary Page
export const STANDARD_ITINERARY_REP_CHANGE = 'STANDARD_ITINERARY_REP_CHANGE';
export const STANDARD_ITINERARY_FORM_OPEN = 'STANDARD_ITINERARY_FORM_OPEN';
export const STANDARD_ITINERARY_FORM_CLOSE = 'STANDARD_ITINERARY_FORM_CLOSE';
export const STANDARD_ITINERARY_CHOOSE_TO_UPDATE = 'STANDARD_ITINERARY_CHOOSE_TO_UPDATE';
export const STANDARD_ITINERARY_DATA_CHANGED = 'STANDARD_ITINERARY_DATA_CHANGED';
export const STANDARD_ITINERARY_NEW_DATE_CHANGED = 'STANDARD_ITINERARY_NEW_DATE_CHANGED';
export const STANDARD_ITINERARY_DIVISION_CHANGE = 'STANDARD_ITINERARY_DIVISION_CHANGE';
export const STANDARD_ITINERARY_TEAM_CHANGE = 'STANDARD_ITINERARY_TEAM_CHANGE';

export const USER_AREA_TAB_CHANGED = 'USER_AREA_TAB_CHANGED';
export const USER_AREA_TERRITORY_LEVELS_LOADED = 'USER_AREA_TERRITORY_LEVELS_LOADED';
export const USER_AREA_TERRITORIES_LOADED = 'USER_AREA_TERRITORIES_LOADED';
export const USER_AREA_TERRITORY_NAME_CHANGE = 'USER_AREA_TERRITORY_NAME_CHANGE';
export const USER_AREA_USERS_LOADED = 'USER_AREA_USERS_LOADED';
export const USER_AREA_USER_NAME_CHANGE = 'USER_AREA_USER_NAME_CHANGE';
export const USER_AREA_USER_MENU_OPEN = 'USER_AREA_USER_MENU_OPEN';
export const USER_AREA_USER_MENU_CLOSE = 'USER_AREA_USER_MENU_CLOSE';
export const USER_AREA_USER_SELECT = 'USER_AREA_USER_SELECT';
export const USER_AREA_USER_TAB_CHANGED = 'USER_AREA_USER_TAB_CHANGED';
export const USER_AREA_LOAD_INFORMATION = 'USER_AREA_LOAD_INFORMATION';
export const USER_AREA_CHANGE_AREA = 'USER_AREA_CHANGE_AREA';

export const USER_CUSTOMERS_LOADED = 'USER_CUSTOMERS_LOADED';
export const USER_CUSTOMER_SUB_TOWN_CHANGE = 'USER_CUSTOMER_SUB_TOWN_CHANGE';
export const USER_CUSTOMER_LEFT_TAB_CHANGE = 'USER_CUSTOMER_LEFT_TAB_CHANGE';
export const USER_CUSTOMER_RIGHT_TAB_CHANGE = 'USER_CUSTOMER_RIGHT_TAB_CHANGE';
export const USER_CUSTOMER_RESULTS_LOADED = 'USER_CUSTOMER_RESULTS_LOADED';
export const USER_CUSTOMER_USERS_LOADED = 'USER_CUSTOMER_USERS_LOADED';
export const USER_CUSTOMER_USER_NAME_CHANGE = 'USER_CUSTOMER_USER_NAME_CHANGE';
export const USER_CUSTOMER_USER_MENU_OPEN = 'USER_CUSTOMER_USER_MENU_OPEN';
export const USER_CUSTOMER_USER_MENU_CLOSE = 'USER_CUSTOMER_USER_MENU_CLOSE';
export const USER_CUSTOMER_USER_SELECT = 'USER_AREA_CUSTOMER_SELECT';
export const USER_CUSTOMER_KEYWORD_CHANGE = 'USER_CUSTOMER_KEYWORD_CHANGE';
export const USER_CUSTOMER_CHEMISTS_CHANGE = 'USER_CUSTOMER_CHEMISTS_CHANGE';
export const USER_CUSTOMER_DOCTORS_CHANGE = 'USER_CUSTOMER_DOCTORS_CHANGE';
export const USER_CUSTOMER_STAFFS_CHANGE = 'USER_CUSTOMER_STAFFS_CHANGE';

// Permission
export const PERMISSION_TYPE_LOADED = 'PERMISSION_TYPE_LOADED';
export const PERMISSION_EXPAND_PANEL = 'PERMISSION_EXPAND_PANEL';
export const PERMISSION_CHANGE_VALUES = 'PERMISSION_CHANGE_VALUES';
export const PERMISSION_CHANGE_TAB = 'PERMISSION_CHANGE_TAB';
export const PERMISSION_CHANGE_KEYWORD = 'PERMISSION_CHANGE_KEYWORD';
export const PERMISSION_RESULTS_LOADED = 'PERMISSION_RESULTS_LOADED';
export const PERMISSION_SELECT_ITEMS = 'PERMISSION_SELECT_ITEMS';
export const PERMISSION_CLEAR_PAGE = 'PERMISSION_CLEAR_PAGE';

// Team Products
export const TEAM_PRODUCT_CHANGE_CHECKED_PRODUCTS = 'TEAM_PRODUCT_CHANGE_CHECKED_PRODUCTS';
export const TEAM_PRODUCT_CHANGE_CHECKED_TEAMS = 'TEAM_PRODUCT_CHANGE_CHECKED_TEAMS';
export const TEAM_PRODUCT_PRODUCTS_LOADED = 'TEAM_PRODUCT_PRODUCTS_LOADED';
export const TEAM_PRODUCT_TEAMS_LOADED = 'TEAM_PRODUCT_TEAMS_LOADED';
export const TEAM_PRODUCT_CHANGE_PRODUCT_NAME = 'TEAM_PRODUCT_CHANGE_PRODUCT_NAME';
export const TEAM_PRODUCT_CHANGE_TEAM_NAME = 'TEAM_PRODUCT_CHANGE_TEAM_NAME';
export const TEAM_PRODUCT_CLEAR_PAGE = 'TEAM_PRODUCT_CLEAR_PAGE';
export const TEAM_PRODUCT_APPEND_CHECKED_PRODUCTS = 'TEAM_PRODUCT_APPEND_CHECKED_PRODUCTS';
export const TEAM_PRODUCT_CHANGE_PRINCIPAL = 'TEAM_PRODUCT_CHANGE_PRINCIPAL';

// Itinerary approval
export const ITINERARY_APPROVAL_CHANGE_TEAM = 'ITINERARY_APPROVAL_CHANGE_TEAM';
export const ITINERARY_APPROVAL_CHANGE_TYPE = 'ITINERARY_APPROVAL_CHANGE_TYPE';
export const ITINERARY_APPROVAL_RESULT_LOADED = 'ITINERARY_APPROVAL_RESULT_LOADED';
export const ITINERARY_APPROVAL_OPEN_ITINERARY = 'ITINERARY_APPROVAL_OPEN_ITINERARY';
export const ITINERARY_APPROVAL_CLOSE_ITINERARY = 'ITINERARY_APPROVAL_CLOSE_ITINERARY';
export const ITINERARY_APPROVAL_CHANGE_DIVISION = 'ITINERARY_APPROVAL_CHANGE_DIVISION';

// Upload CSV files
export const UPLOAD_CSV_CHANGE_TYPE = 'UPLOAD_CSV_CHANGE_TYPE';
export const UPLOAD_CSV_CHANGE_INFO = 'UPLOAD_CSV_CHANGE_INFO';
export const UPLOAD_CSV_CHANGE_FILE = 'UPLOAD_CSV_CHANGE_FILE';
export const UPLOAD_CSV_CHANGE_STATUS = 'UPLOAD_CSV_CHANGE_STATUS';
export const UPLOAD_CSV_SUBMITED = 'UPLOAD_CSV_SUBMITED';
export const UPLOAD_CSV_CLEAR_PAGE = 'UPLOAD_CSV_CLEAR_PAGE';

// Issue Tracker
export const ISSUE_TRACKER_CHANGE_LABEL = 'ISSUE_TRACKER_CHANGE_LABEL';
export const ISSUE_TRACKER_CLEAR_PAGE = 'ISSUE_TRACKER_CLEAR_PAGE';
export const ISSUE_TRACKER_CHANGE_CONTENT = 'ISSUE_TRACKER_CHANGE_CONTENT';
export const ISSUE_TRACKER_ISSUES_LOADED = 'ISSUE_TRACKER_ISSUES_LOADED';
export const ISSUE_TRACKER_CHANGE_TYPE = 'ISSUE_TRACKER_CHANGE_TYPE';
export const ISSUE_TRACKER_CHANGE_PAGE = 'ISSUE_TRACKER_CHANGE_PAGE';

// User targets
export const TARGET_CHANGE_TYPE = 'TARGET_CHANGE_TYPE';
export const TARGET_CHANGE_REP = 'TARGET_CHANGE_REP';
export const TARGET_CHANGE_MAIN_VALUE = 'TARGET_CHANGE_MAIN_VALUE';
export const TARGET_CHANGE_MAIN_QTY = 'TARGET_CHANGE_MAIN_QTY';
export const TARGET_DATA_LOADED = 'TARGET_DATA_LOADED';
export const TARGET_CHANGE_ITEM_TARGET = 'TARGET_CHANGE_ITEM_TARGET';
export const TARGET_CLEAR_PAGE = 'TARGET_CLEAR_PAGE';
export const TARGET_CHANGE_DATE = 'TARGET_CHANGE_DATE';
export const TARGET_MENU_OPEN = 'TARGET_MENU_OPEN';
export const TARGET_MENU_CLOSE = 'TARGET_MENU_CLOSE';

// Doctor approve
export const DOC_APRV_CHANGE_USER = 'DOC_APRV_CHANGE_USER';
export const DOC_APRV_CHANGE_FROM_DATE = 'DOC_APRV_CHANGE_FROM_DATE';
export const DOC_APRV_CHANGE_TO_DATE = 'DOC_APRV_CHANGE_TO_DATE';
export const DOC_APRV_DATA_LOADED = 'DOC_APRV_DATA_LOADED';
export const DOC_APRV_SELECT_TO_EDIT = 'DOC_APRV_SELECT_TO_EDIT';
export const DOC_APRV_CHANGE_DOCTOR = 'DOC_APRV_CHANGE_DOCTOR';

//Expenses Statement Report
export const EXP_STMNT_LOAD_TYPES = 'EXP_STMNT_LOAD_TYPES';
export const EXP_STMNT_LOAD_RESULTS = 'EXP_STMNT_LOAD_RESULTS';
export const EXP_STMNT_CHANGE_VALUE = 'EXP_STMNT_CHANGE_VALUE';
export const EXP_STMNT_LOAD_BATA_TYPES = 'EXP_STMNT_LOAD_BATA_TYPES';
export const EXP_STMNT_LOAD_BATA_CAT = 'EXP_STMNT_LOAD_BATA_CAT';

export const ITINERARY_VIEW_CHANGE_USER = 'ITINERARY_VIEW_CHANGE_USER';
export const ITINERARY_VIEW_CHANGE_DATE = 'ITINERARY_VIEW_CHANGE_DATE';
export const ITINERARY_VIEW_LOAD_ITINERARIES = 'ITINERARY_VIEW_LOAD_ITINERARIES';
export const ITINERARY_VIEW_LOAD_ITINERARY = 'ITINERARY_VIEW_LOAD_ITINERARY';
export const ITINERARY_VIEW_CALENDAR_OPEN = 'ITINERARY_VIEW_CALENDAR_OPEN';
export const ITINERARY_VIEW_CALENDAR_CLOSE = 'ITINERARY_VIEW_CALENDAR_CLOSE';

// Fm Level Report
export const FM_LEVEL_LOAD_VALUES = 'FM_LEVEL_LOAD_VALUES';
export const FM_LEVEL_LOAD_RESULT = 'FM_LEVEL_LOAD_RESULT';

//Mr Ps Itinerary Report
export const MR_PS_REPORT_LOAD_VALUES = 'MR_PS_REPORT_LOAD_VALUES';
export const MR_PS_REPORT_LOAD_RESULT = 'MR_PS_REPORT_LOAD_RESULT';

//Ytd Sales Sheet Report
export const YTD_SALES_SHEET_REPORT_LOAD_VALUES = 'YTD_SALES_SHEET_REPORT_LOAD_VALUES';
export const YTD_SALES_SHEET_REPORT_LOAD_RESULT = 'YTD_SALES_SHEET_REPORT_LOAD_VALUES_LOAD_RESULT';
export const YTD_SALES_SHEET_REPORT_PAGE_NUMBER = 'YTD_SALES_SHEET_REPORT_PAGE_NUMBER';
export const YTD_SALES_SHEET_REPORT_ROWS_COUNT = 'YTD_SALES_SHEET_REPORT_ROWS_COUNT';
export const YTD_SALES_SHEET_REPORT_ORDER_BY_CHANGE = 'YTD_SALES_SHEET_REPORT_ORDER_BY_CHANGE';
export const YTD_SALES_SHEET_REPORT_LOADING = 'YTD_SALES_SHEET_REPORT_LOADING';

export const USER_CLONE_CHANGE_USER = 'USER_CLONE_CHANGE_USER';
export const USER_CLONE_CHANGE_SELECTED_TYPES = 'USER_CLONE_CHANGE_SELECTED_TYPES';
export const USER_CLONE_LOAD_SECTIONS = 'USER_CLONE_LOAD_SECTIONS';
export const USER_CLONE_CHANGE_VALUES = 'USER_CLONE_CHANGE_VALUES';
export const USER_CLONE_RESET = 'USER_CLONE_RESET';

//Doctor Towns Allocations
export const DOCTOR_TOWNS_TOWNS_LOADED = 'DOCTOR_TOWNS_TOWNS_LOADED';
export const DOCTOR_TOWNS_DOCTORS_LOADED = 'DOCTOR_TOWNS_DOCTORS_LOADED';
export const DOCTOR_TOWNS_SELECT_TOWNS = 'DOCTOR_TOWNS_SELECT_TOWNS';
export const DOCTOR_TOWNS_SELECT_DOCTORS = 'DOCTOR_TOWNS_SELECT_DOCTORS';
export const DCOTOR_TOWNS_APPEND_TOWNS = 'DCOTOR_TOWNS_APPEND_TOWNS';
export const DOCTOR_TOWNS_CLEAR_SELECTIONS = 'DOCTOR_TOWNS_CLEAR_SELECTIONS';

//User allocations
export const USER_ALLOCATIONS_USER_CHANGE = 'USER_ALLOCATIONS_USER_CHANGE';

// Route Chemist
export const ROUTE_CHEMIST_LOADED_CHEMISTS = 'ROUTE_CHEMIST_LOADED_CHEMISTS';
export const ROUTE_CHEMIST_LOADED_ROUTES = 'ROUTE_CHEMIST_LOADED_ROUTES';
export const ROUTE_CHEMIST_ADD_ROUTES = 'ROUTE_CHEMIST_ADD_ROUTES';
export const ROUTE_CHEMIST_ADD_CHEMISTS = 'ROUTE_CHEMIST_ADD_CHEMISTS';
export const ROUTE_CHEMIST_REMOVE_ROUTES = 'ROUTE_CHEMIST_REMOVE_ROUTES';
export const ROUTE_CHEMIST_REMOVE_CHEMISTS = 'ROUTE_CHEMIST_REMOVE_CHEMISTS';
export const ROUTE_CHEMIST_CHANGE_CHEMIST_KEYWORD = 'ROUTE_CHEMIST_CHANGE_CHEMIST_KEYWORD';
export const ROUTE_CHEMIST_CHANGE_ROUTE_KEYWORD = 'ROUTE_CHEMIST_CHANGE_ROUTE_KEYWORD';
export const ROUTE_CHEMIST_CLEAR_PAGE = 'ROUTE_CHEMIST_CLEAR_PAGE';
export const ROUTE_CHEMIST_LOADED_CHECKED_CHEMISTS = 'ROUTE_CHEMIST_LOADED_CHECKED_CHEMISTS';
export const ROUTE_CHEMIST_AREA_CHANGE = 'ROUTE_CHEMIST_AREA_CHANGE';
export const ROUTE_CHEMIST_TYPE_CHANGE = 'ROUTE_CHEMIST_TYPE_CHANGE';

// Sales Itinerary
export const SALES_ITINERARY_LOAD = 'SALES_ITINERARY_LOAD';
export const SALES_ITINERARY_DATE_SELECT = 'SALES_ITINERARY_DATE_SELECT';
export const SALES_ITINERARY_DAY_TYPE_SELECT = 'SALES_ITINERARY_DAY_TYPE_SELECT';
export const SALES_ITINERARY_DAY_TYPE_UNSELECT = 'SALES_ITINERARY_DAY_TYPE_UNSELECT';
export const SALES_ITINERARY_CHANGE_DATE = 'SALES_ITINERARY_CHANGE_DATE';
export const SALES_ITINERARY_CLEAR_DATE = 'SALES_ITINERARY_CLEAR_DATE';
export const SALES_ITINERARY_USER_CHANGE = 'SALES_ITINERARY_USER_CHANGE';
export const SALES_ITINERARY_MODE_CHANGE = 'SALES_ITINERARY_MODE_CHANGE';
export const SALES_ITINERARY_UPDATING_VALUES_CHANGE = 'SALES_ITINERARY_UPDATING_VALUES_CHANGE';
export const SALES_ITINERARY_UPDATING_VALUES_CANCEL = 'SALES_ITINERARY_UPDATING_VALUES_CANCEL';
export const SALES_ITINERARY_AREA_CHANGE = 'SALES_ITINERARY_AREA_CHANGE';
export const SALES_ITINERARY_TYPE_CHANGE = 'SALES_ITINERARY_TYPE_CHANGE';

// Sales Allocation
export const SALES_ALLOCATION_CHANGE_TEAM = 'SALES_ALLOCATION_CHANGE_TEAM';
export const SALES_ALLOCATION_CHANGE_MODE = 'SALES_ALLOCATION_CHANGE_MODE';
export const SALES_ALLOCATION_LOAD_DATA = 'SALES_ALLOCATION_LOAD_DATA';
export const SALES_ALLOCATION_CHANGE_UPDATING_MODE = 'SALES_ALLOCATION_CHANGE_UPDATING_MODE';
export const SALES_ALLOCATION_LOAD_SECTION_DATA = 'SALES_ALLOCATION_LOAD_SECTION_DATA';
export const SALES_ALLOCATION_SELECT_ROW = 'SALES_ALLOCATION_SELECT_ROW';
export const SALES_ALLOCATION_CHANGE_SEARCH_TERM = 'SALES_ALLOCATION_CHANGE_SEARCH_TERM';
export const SALES_ALLOCATION_CHANGE_PAGE = 'SALES_ALLOCATION_CHANGE_PAGE';
export const SALES_ALLOCATION_CHANGE_PER_PAGE = 'SALES_ALLOCATION_CHANGE_PER_PAGE';
export const SALES_ALLOCATION_CHANGE_MEMBER_PERCENTAGE = 'SALES_ALLOCATION_CHANGE_MEMBER_PERCENTAGE';

// Invoice Allocation
export const INVOICE_ALLOCATION_CHANGE_TEAM = 'INVOICE_ALLOCATION_CHANGE_TEAM';
export const INVOICE_ALLOCATION_CHANGE_MODE = 'INVOICE_ALLOCATION_CHANGE_MODE';
export const INVOICE_ALLOCATION_SELECT_INVOICE = 'INVOICE_ALLOCATION_SELECT_INVOICE';
export const INVOICE_ALLOCATION_LOAD_DATA = 'INVOICE_ALLOCATION_LOAD_DATA';
export const INVOICE_ALLOCATION_CHANGE_PAGE = 'INVOICE_ALLOCATION_CHANGE_PAGE';
export const INVOICE_ALLOCATION_CHANGE_PER_PAGE = 'INVOICE_ALLOCATION_CHANGE_PER_PAGE';
export const INVOICE_ALLOCATION_LOAD_SEARCH_RESULTS = 'INVOICE_ALLOCATION_LOAD_SEARCH_RESULTS';
export const INVOICE_ALLOCATION_CHANGE_VALUES = 'INVOICE_ALLOCATION_CHANGE_VALUES';
export const INVOICE_ALLOCATION_CHANGE_PANEL = 'INVOICE_ALLOCATION_CHANGE_PANEL';
export const INVOICE_ALLOCATION_CHANGE_PRODUCT_MODE = 'INVOICE_ALLOCATION_CHANGE_PRODUCT_MODE';
export const INVOICE_ALLOCATION_CHECK_PRODUCTS = 'INVOICE_ALLOCATION_CHECK_PRODUCTS';
export const INVOICE_ALLOCATION_LOAD_PRODUCTS = 'INVOICE_ALLOCATION_LOAD_PRODUCTS';
export const INVOICE_ALLOCATION_CHANGE_PRODUCTS_PAGE = 'INVOICE_ALLOCATION_CHANGE_PRODUCTS_PAGE';
export const INVOICE_ALLOCATION_CHANGE_PRODUCTS_PER_PAGE = 'INVOICE_ALLOCATION_CHANGE_PRODUCTS_PER_PAGE';
export const INVOICE_ALLOCATION_CHANGE_PRODUCT_KEYWORD = 'INVOICE_ALLOCATION_CHANGE_PRODUCT_KEYWORD';
export const INVOICE_ALLOCATION_CHANGE_MEMBER_QTY = 'INVOICE_ALLOCATION_CHANGE_MEMBER_QTY';

// Team Performance Report
export const TEAM_PERFORMANCE_REPORT_LOAD_VALUES = 'TEAM_PERFORMANCE_REPORT_LOAD_VALUES';
export const TEAM_PERFORMANCE_REPORT_LOAD_RESULT = 'TEAM_PERFORMANCE_REPORT_LOAD_VALUES_LOAD_RESULT';
export const TEAM_PERFORMANCE_REPORT_PAGE = 'TEAM_PERFORMANCE_REPORT_PAGE';
export const TEAM_PERFORMANCE_REPORT_PERPAGE = 'TEAM_PERFORMANCE_REPORT_PERPAGE';

// Sales Itinerary Approval
export const SALES_ITINERARY_APPROVAL_CHANGE_USER = 'SALES_ITINERARY_APPROVAL_CHANGE_USER';
export const SALES_ITINERARY_APPROVAL_CHANGE_TYPE = 'SALES_ITINERARY_APPROVAL_CHANGE_TYPE';
export const SALES_ITINERARY_APPROVAL_RESULT_LOADED = 'SALES_ITINERARY_APPROVAL_RESULT_LOADED';
export const SALES_ITINERARY_APPROVAL_OPEN_ITINERARY = 'SALES_ITINERARY_APPROVAL_OPEN_ITINERARY';
export const SALES_ITINERARY_APPROVAL_CLOSE_ITINERARY = 'SALES_ITINERARY_APPROVAL_CLOSE_ITINERARY';
export const SALES_ITINERARY_APPROVAL_CHANGE_DIVISION = 'SALES_ITINERARY_APPROVAL_CHANGE_DIVISION';
export const SALES_ITINERARY_APPROVAL_CHANGE_AREA = 'SALES_ITINERARY_APPROVAL_CHANGE_AREA';
export const SALES_ITINERARY_APPROVAL_CHANGE_MODE = 'SALES_ITINERARY_APPROVAL_CHANGE_MODE';

// Team Wise Sales Report
export const TEAM_WISE_SALES_REPORT_LOAD_VALUES = 'TEAM_WISE_SALES_REPORT_LOAD_VALUES';
export const TEAM_WISE_SALES_REPORT_LOAD_RESULT = 'TEAM_WISE_SALES_REPORT_LOAD_VALUES_LOAD_RESULT';

// Sales GPS Tracking
export const SALES_GPS_USER_CHANGE = 'SALES_GPS_USER_CHANGE';
export const SALES_GPS_DATE_CHANGE = 'SALES_GPS_DATE_CHANGE';
export const SALES_GPS_DATA_LOADED = 'SALES_GPS_DATA_LOADED';
export const SALES_GPS_TIME_CHANGE = 'SALES_GPS_TIME_CHANGE';

// Sales Target
export const SALES_TARGET_DATA_LOADED = 'SALES_TARGET_DATA_LOADED';
export const SALES_TARGET_CLEAR_PAGE = 'SALES_TARGET_CLEAR_PAGE';
export const SALES_TARGET_CHANGE_DATE = 'SALES_TARGET_CHANGE_DATE';
export const SALES_TARGET_CHANGE_ITEM_TARGET = 'SALES_TARGET_CHANGE_ITEM_TARGET';

//Sales Weekly Target Allocation
export const SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_REP = 'SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_REP';
export const SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_PREASANTAGE = 'SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_PREASANTAGE';
export const SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_MONTH = 'SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_MONTH';
export const SALES_WEEKLY_TARGET_ALLOCATION_LOAD_QTY_VALUE = 'SALES_WEEKLY_TARGET_ALLOCATION_LOAD_QTY_VALUE';
export const SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_TARGET = 'SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_TARGET';
export const SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_PLUS = 'SALES_WEEKLY_TARGET_ALLOCATION_CHANGE_PLUS';
export const SALES_WEEKLY_TARGET_ALLOCATION_PLUS_COUNT = 'SALES_WEEKLY_TARGET_ALLOCATION_PLUS_COUNT';
export const SALES_WEEKLY_TARGET_ALLOCATION_PREASANTAGE_CAL = 'SALES_WEEKLY_TARGET_ALLOCATION_PREASANTAGE_CAL';
export const SALES_WEEKLY_TARGET_ALLOCATION_CHECK_MONTHLY_TARGET_EXCEEDED = 'SALES_WEEKLY_TARGET_ALLOCATION_CHECK_MONTHLY_TARGET_EXCEEDED';
export const SALES_WEEKLY_TARGET_ALLOCATION_CHECK_ERROR = 'SALES_WEEKLY_TARGET_ALLOCATION_CHECK_ERROR';
export const SALES_WEEKLY_TARGET_ALLOCATION_CHECK_TYPE = 'SALES_WEEKLY_TARGET_ALLOCATION_CHECK_TYPE';
export const SALES_WEEKLY_TARGET_ALLOCATION_DROP_WEEK = 'SALES_WEEKLY_TARGET_ALLOCATION_DROP_WEEK';
export const SALES_WEEKLY_TARGET_ALLOCATION_PAGE_CLEAR = 'SALES_WEEKLY_TARGET_ALLOCATION_PAGE_CLEAR';

// SR CUSTOMER allocation
export const SR_CUSTOMER_LOADED_CUSTOMERS = 'SR_CUSTOMER_LOADED_CUSTOMERS';
export const SR_CUSTOMER_LOADED_SRS = 'SR_CUSTOMER_LOADED_SRS';
export const SR_CUSTOMER_ADD_SRS = 'SR_CUSTOMER_ADD_SRS';
export const SR_CUSTOMER_ADD_CUSTOMERS = 'SR_CUSTOMER_ADD_CUSTOMERS';
export const SR_CUSTOMER_REMOVE_SRS = 'SR_CUSTOMER_REMOVE_SRS';
export const SR_CUSTOMER_REMOVE_CUSTOMERS = 'SR_CUSTOMER_REMOVE_CUSTOMERS';
export const SR_CUSTOMER_CHANGE_CUSTOMER_KEYWORD = 'SR_CUSTOMER_CHANGE_CUSTOMER_KEYWORD';
export const SR_CUSTOMER_CHANGE_SR_KEYWORD = 'SR_CUSTOMER_CHANGE_SR_KEYWORD';
export const SR_CUSTOMER_CLEAR_PAGE = 'SR_CUSTOMER_CLEAR_PAGE';
export const SR_CUSTOMER_LOADED_CHECKED_CUSTOMERS = 'SR_CUSTOMER_LOADED_CHECKED_CUSTOMERS';


// expenses edit
export const SALES_EXPENSES_EDIT_CHANGE_REP = 'SALES_EXPENSES_EDIT_CHANGE_REP';
export const SALES_EXPENSES_EDIT_CHANGE_MONTH = 'SALES_EXPENSES_EDIT_CHANGE_MONTH';
export const SALES_EXPENSES_EDIT_CHANGE_DATA = 'SALES_EXPENSES_EDIT_CHANGE_DATA';
export const SALES_EXPENSES_EDIT_LOAD_DATA = 'SALES_EXPENSES_EDIT_LOAD_DATA';
export const SALES_EXPENSES_EDIT_PLUS_DATA = 'SALES_EXPENSES_EDIT_PLUS_DATA';
export const SALES_EXPENSES_OPEN_MODAL = 'SALES_EXPENSES_OPEN_MODAL';
export const SALES_EXPENSES_CHANGE_VALUE = 'SALES_EXPENSES_CHANGE_VALUE';
export const SALES_EXPENSES_ASM_ROLL = 'SALES_EXPENSES_ASM_ROLL';

// Purchase order
export const PURCHASE_ORDER_DISTRIBUTOR_CHANGE = 'PURCHASE_ORDER_DISTRIBUTOR_CHANGE';
export const PURCHASE_ORDER_NUMBER_CHANGE = 'PURCHASE_ORDER_NUMBER_CHANGE';
export const PURCHASE_ORDER_PRODUCT_CHANGE = 'PURCHASE_ORDER_PRODUCT_CHANGE';
export const PURCHASE_ORDER_QTY_CHANGE = 'PURCHASE_ORDER_QTY_CHANGE';
export const PURCHASE_ORDER_REMOVE_LINE = 'PURCHASE_ORDER_REMOVE_LINE';
export const PURCHASE_ORDER_DETAILS_CHANGE = 'PURCHASE_ORDER_DETAILS_CHANGE';
export const PURCHASE_ORDER_ADD_LINE = 'PURCHASE_ORDER_ADD_LINE';
export const PURCHASE_ORDER_CLEAR_PAGE = 'PURCHASE_ORDER_CLEAR_PAGE';
export const PURCHASE_ORDER_DSR_CHANGE = 'PURCHASE_ORDER_DSR_CHANGE';
export const PURCHASE_ORDER_SITE_CHANGE = 'PURCHASE_ORDER_SITE_CHANGE';
export const PURCHASE_ORDER_LOADING =  'PURCHASE_ORDER_LOADING';

// DCR SR Allocation
export const SR_ALLOCATION_CHANGE_CHECKED_DSR = 'SR_ALLOCATION_CHANGE_CHECKED_DSR';
export const SR_ALLOCATION_CHANGE_CHECKED_SR = 'SR_ALLOCATION_CHANGE_CHECKED_SR';
export const SR_ALLOCATION_DSR_LOADED = 'SR_ALLOCATION_DSR_LOADED';
export const SR_ALLOCATION_SR_LOADED = 'SR_ALLOCATION_SR_LOADED';
export const SR_ALLOCATION_CHANGE_DCR_NAME = 'SR_ALLOCATION_CHANGE_DCR_NAME';
export const SR_ALLOCATION_CHANGE_SR_NAME = 'SR_ALLOCATION_CHANGE_SR_NAME';
export const SR_ALLOCATION_CLEAR_PAGE = 'SR_ALLOCATION_CLEAR_PAGE';
export const SR_ALLOCATION_APPEND_CHECKED_SR = 'SR_ALLOCATION_APPEND_CHECKED_SR';

// DCR Site Allocation
export const SITE_ALLOCATION_CHANGE_CHECKED_DSR = 'SITE_ALLOCATION_CHANGE_CHECKED_DSR';
export const SITE_ALLOCATION_CHANGE_CHECKED_SITE = 'SITE_ALLOCATION_CHANGE_CHECKED_SITE';
export const SITE_ALLOCATION_DSR_LOADED = 'SITE_ALLOCATION_DSR_LOADED';
export const SITE_ALLOCATION_SITE_LOADED = 'SITE_ALLOCATION_SITE_LOADED';
export const SITE_ALLOCATION_CHANGE_DSR_NAME = 'SITE_ALLOCATION_CHANGE_DSR_NAME';
export const SITE_ALLOCATION_CHANGE_SITE_NAME = 'SITE_ALLOCATION_CHANGE_SITE_NAME';
export const SITE_ALLOCATION_CLEAR_PAGE = 'SITE_ALLOCATION_CLEAR_PAGE';
export const SITE_ALLOCATION_APPEND_CHECKED_SITE = 'SITE_ALLOCATION_APPEND_CHECKED_SITE';

// SR PRODUCT allocation
export const SR_PRODUCT_LOADED_PRODUCTS = 'SR_PRODUCT_LOADED_PRODUCTS';
export const SR_PRODUCT_LOADED_SRS = 'SR_PRODUCT_LOADED_SRS';
export const SR_PRODUCT_ADD_SRS = 'SR_PRODUCT_ADD_SRS';
export const SR_PRODUCT_ADD_PRODUCTS = 'SR_PRODUCT_ADD_PRODUCTS';
export const SR_PRODUCT_REMOVE_SRS = 'SR_PRODUCT_REMOVE_SRS';
export const SR_PRODUCT_REMOVE_PRODUCTS = 'SR_PRODUCT_REMOVE_PRODUCTS';
export const SR_PRODUCT_CHANGE_PRODUCT_KEYWORD = 'SR_PRODUCT_CHANGE_PRODUCT_KEYWORD';
export const SR_PRODUCT_CHANGE_SR_KEYWORD = 'SR_PRODUCT_CHANGE_SR_KEYWORD';
export const SR_PRODUCT_CLEAR_PAGE = 'SR_PRODUCT_CLEAR_PAGE';
export const SR_PRODUCT_LOADED_CHECKED_PRODUCTS = 'SR_PRODUCT_LOADED_CHECKED_PRODUCTS';

// Invoice Creation
export const INVOICE_CREATION_CHANGE_SO_NUMBER = 'INVOICE_CHANGE_SALES_ORDER_NUMBER';
export const INVOICE_CREATION_LOAD_SO_DETAILS = 'INVOICE_CREATION_LOAD_SO_DETAILS';
export const INVOICE_CREATION_CHANGE_QTY = 'INVOICE_CREATION_CHANGE_QTY';
export const INVOICE_CREATION_CHANGE_DISCOUNT = 'INVOICE_CREATION_CHANGE_DISCOUNT';
export const INVOICE_CREATION_CLEAR_PAGE = 'INVOICE_CREATION_CLEAR_PAGE';
export const INVOICE_CREATION_LOAD_BONUS = 'INVOICE_CREATION_LOAD_BONUS';
export const INVOICE_CREATION_CHANGE_BONUS_QTY = 'INVOICE_CREATION_CHANGE_BONUS_QTY';
export const INVOICE_CREATION_LOAD_BATCH_DETAILS = 'INVOICE_CREATION_LOAD_BATCH_DETAILS';
export const INVOICE_CREATION_OPEN_BATCH_EDIT_FORM = 'INVOICE_CREATION_OPEN_BATCH_EDIT_FORM';
export const INVOICE_CREATION_CHANGE_BATCH_QTY = 'INVOICE_CREATION_CHANGE_BATCH_QTY';
export const INVOICE_CREATION_CANCEL_BATCH_EDIT_FORM = 'INVOICE_CREATION_CANCEL_BATCH_EDIT_FORM';

// DCR SALESMAN Allocation
export const SALESMAN_ALLOCATION_CHANGE_CHECKED_DSR = 'SALESMAN_ALLOCATION_CHANGE_CHECKED_DSR';
export const SALESMAN_ALLOCATION_CHANGE_CHECKED_SR = 'SALESMAN_ALLOCATION_CHANGE_CHECKED_SR';
export const SALESMAN_ALLOCATION_DSR_LOADED = 'SALESMAN_ALLOCATION_DSR_LOADED';
export const SALESMAN_ALLOCATION_SR_LOADED = 'SALESMAN_ALLOCATION_SR_LOADED';
export const SALESMAN_ALLOCATION_CHANGE_DCR_NAME = 'SALESMAN_ALLOCATION_CHANGE_DCR_NAME';
export const SALESMAN_ALLOCATION_CHANGE_SR_NAME = 'SALESMAN_ALLOCATION_CHANGE_SR_NAME';
export const SALESMAN_ALLOCATION_CLEAR_PAGE = 'SALESMAN_ALLOCATION_CLEAR_PAGE';
export const SALESMAN_ALLOCATION_APPEND_CHECKED_SR = 'SALESMAN_ALLOCATION_APPEND_CHECKED_SR';

// Stock Adjusment
export const STOCK_ADJUSMENT_CHANGE_TYPE = 'STOCK_ADJUSMENT_CHANGE_TYPE';
export const STOCK_ADJUSMENT_LOAD_NO = 'STOCK_ADJUSMENT_LOAD_NO';
export const STOCK_ADJUSMENT_FETCH_NO = 'STOCK_ADJUSMENT_FETCH_NO';
export const STOCK_ADJUSMENT_CHANGE_DIS = 'STOCK_ADJUSMENT_CHANGE_DIS';
export const STOCK_ADJUSMENT_LOAD_DATA = 'STOCK_ADJUSMENT_LOAD_DATA';
export const STOCK_ADJUSMENT_CHANGE_DATA = 'STOCK_ADJUSMENT_CHANGE_DATA';
export const STOCK_ADJUSMENT_AJUST_QTY = 'STOCK_ADJUSMENT_AJUST_QTY';

// Direct Invoice
export const DIRECT_INVOICE_CHANGE_DISTRIBUTOR = 'DIRECT_INVOICE_CHANGE_DISTRIBUTOR';
export const DIRECT_INVOICE_CHANGE_SALESMAN = 'DIRECT_INVOICE_CHANGE_SALESMAN';
export const DIRECT_INVOICE_CHANGE_CUSTOMER = 'DIRECT_INVOICE_CHANGE_CUSTOMER';
export const DIRECT_INVOICE_CHANGE_CHANGE_INVOICE_NUMBER = 'DIRECT_INVOICE_CHANGE_CHANGE_INVOICE_NUMBER';
export const DIRECT_INVOICE_ADD_LINE = 'DIRECT_INVOICE_ADD_LINE';
export const DIRECT_INVOICE_REMOVE_LINE = 'DIRECT_INVOICE_REMOVE_LINE';
export const DIRECT_INVOICE_CHANGE_DISCOUNT = 'DIRECT_INVOICE_CHANGE_DISCOUNT';
export const DIRECT_INVOICE_CHANGE_PRODUCT = 'DIRECT_INVOICE_CHANGE_PRODUCT';
export const DIRECT_INVOICE_LOAD_LINE_INFO = 'DIRECT_INVOICE_LOAD_LINE_INFO';
export const DIRECT_INVOICE_CHANGE_QTY = 'DIRECT_INVOICE_CHANGE_QTY';
export const DIRECT_INVOICE_CLEAR_PAGE = 'DIRECT_INVOICE_CLEAR_PAGE';
export const DIRECT_INVOICE_LOAD_BONUS_DATA = 'DIRECT_INVOICE_LOAD_BONUS_DATA';
export const DIRECT_INVOICE_CHANGE_BONUS_QTY = 'DIRECT_INVOICE_CHANGE_BONUS_QTY';
export const DIRECT_INVOICE_LOAD_BATCH_DETAILS = 'DIRECT_INVOICE_LOAD_BATCH_DETAILS';
export const DIRECT_INVOICE_OPEN_BATCH_EDIT_FORM = 'DIRECT_INVOICE_OPEN_BATCH_EDIT_FORM';
export const DIRECT_INVOICE_CHANGE_BATCH_QTY = 'DIRECT_INVOICE_CHANGE_BATCH_QTY';
export const DIRECT_INVOICE_CANCEL_BATCH_EDIT_FORM = 'DIRECT_INVOICE_CANCEL_BATCH_EDIT_FORM';


// GRN Confirm
export const GRN_CONFIRM_CHANGE_GRN_NO = 'GRN_CONFIRM_CHANGE_GRN_NO';
export const GRN_CONFIRM_LOAD_PRODUCTS = 'GRN_CONFIRM_LOAD_PRODUCTS';
export const GRN_CONFIRM_CLEAR_PAGE = 'GRN_CONFIRM_CLEAR_PAGE';
export const GRN_CONFIRM_CHANGE_QTY = 'GRN_CONFIRM_CHANGE_QTY';

// Change User Password
export const USER_CHANGE_PASS_LOAD_DATA = 'USER_CHANGE_PASS_LOAD_DATA';
export const USER_CHANGE_PASS_CHANGE_PASSWORD = 'USER_CHANGE_PASS_CHANGE_PASSWORD';
export const USER_CHANGE_PASS_CHANGE_LOCK_TIME = 'USER_CHANGE_PASS_CHANGE_LOCK_TIME';
export const USER_CHANGE_PASS_CHANGE_ATTEMPTS = 'USER_CHANGE_PASS_CHANGE_ATTEMPTS';
export const USER_CHANGE_PASS_LOAD_OTHER = 'USER_CHANGE_PASS_LOAD_OTHER';
export const STOCK_ADJUSMENT_PAGE_CLEAR = 'STOCK_ADJUSMENT_PAGE_CLEAR';

// Create Return
export const CREATE_RETURN_CHANGE_DISTRIBUTOR = 'CREATE_RETURN_CHANGE_DISTRIBUTOR';
export const CREATE_RETURN_CHANGE_SALESMAN = 'CREATE_RETURN_CHANGE_SALESMAN';
export const CREATE_RETURN_CHANGE_CUSTOMER = 'CREATE_RETURN_CHANGE_CUSTOMER';
export const CREATE_RETURN_CHANGE_CHANGE_INVOICE_NUMBER = 'CREATE_RETURN_CHANGE_CHANGE_INVOICE_NUMBER';
export const CREATE_RETURN_ADD_LINE = 'CREATE_RETURN_ADD_LINE';
export const CREATE_RETURN_REMOVE_LINE = 'CREATE_RETURN_REMOVE_LINE';
export const CREATE_RETURN_CHANGE_DISCOUNT = 'CREATE_RETURN_CHANGE_DISCOUNT';
export const CREATE_RETURN_CHANGE_PRODUCT = 'CREATE_RETURN_CHANGE_PRODUCT';
export const CREATE_RETURN_LOAD_LINE_INFO = 'CREATE_RETURN_LOAD_LINE_INFO';
export const CREATE_RETURN_CHANGE_QTY = 'CREATE_RETURN_CHANGE_QTY';
export const CREATE_RETURN_CLEAR_PAGE = 'CREATE_RETURN_CLEAR_PAGE';
export const CREATE_RETURN_LOAD_BONUS_DATA = 'CREATE_RETURN_LOAD_BONUS_DATA';
export const CREATE_RETURN_CHANGE_BONUS_QTY = 'CREATE_RETURN_CHANGE_BONUS_QTY';
export const CREATE_RETURN_CHANGE_SALABLE = 'CREATE_RETURN_CHANGE_SALABLE';
export const CREATE_RETURN_CHANGE_REASON = 'CREATE_RETURN_CHANGE_REASON';
export const CREATE_RETURN_CHANGE_BATCH = 'CREATE_RETURN_CHANGE_BATCH';
export const CREATE_RETURN_CHANGE_BONUS_BATCH = 'CREATE_RETURN_CHANGE_BONUS_BATCH';

// Sales Data Process
export const SALES_DATA_PROCESS_CHANGE_MONTH = 'SALES_DATA_PROCESS_CHANGE_MONTH';
export const SALES_DATA_PROCESS_CHANGE_PERCENTAGE = 'SALES_DATA_PROCESS_CHANGE_PERCENTAGE';

// Order Based Return
export const ORDER_BASED_RETURN_CHANGE_INVOICE_NUMBER = 'ORDER_BASED_RETURN_CHANGE_INVOICE_NUMBER';
export const ORDER_BASED_RETURN_LOAD_INVOICE_INFO = 'ORDER_BASED_RETURN_LOAD_INVOICE_INFO';
export const ORDER_BASED_RETURN_LOAD_BONUS_DETAILS = 'ORDER_BASED_RETURN_LOAD_BONUS_DETAILS';
export const ORDER_BASED_RETURN_CHANGE_QTY = 'ORDER_BASED_RETURN_CHANGE_QTY';
export const ORDER_BASED_RETURN_CHANGE_REASON = 'ORDER_BASED_RETURN_CHANGE_REASON';
export const ORDER_BASED_RETURN_CHANGE_SALABLE = 'ORDER_BASED_RETURN_CHANGE_SALABLE';
export const ORDER_BASED_RETURN_CLEAR_PAGE = 'ORDER_BASED_RETURN_CLEAR_PAGE';
export const ORDER_BASED_RETURN_CHANGE_BONUS_QTY = 'ORDER_BASED_RETURN_CHANGE_BONUS_QTY';

// Purchase order confirm
export const PURCHASE_ORDER_CONFIRM_NUMBER_CHANGE = 'PURCHASE_ORDER_NUMBER_CHANGE';
export const PURCHASE_ORDER_CONFIRM_PRODUCT_CHANGE = 'PURCHASE_ORDER_PRODUCT_CHANGE';
export const PURCHASE_ORDER_CONFIRM_QTY_CHANGE = 'PURCHASE_ORDER_QTY_CHANGE';
export const PURCHASE_ORDER_CONFIRM_REMOVE_LINE = 'PURCHASE_ORDER_REMOVE_LINE';
export const PURCHASE_ORDER_CONFIRM_DETAILS_CHANGE = 'PURCHASE_ORDER_DETAILS_CHANGE';
export const PURCHASE_ORDER_CONFIRM_ADD_LINE = 'PURCHASE_ORDER_ADD_LINE';
export const PURCHASE_ORDER_CONFIRM_CLEAR_PAGE = 'PURCHASE_ORDER_CLEAR_PAGE';
export const PURCHASE_ORDER_CONFIRM_LOAD_DATA = 'PURCHASE_ORDER_CONFIRM_LOAD_DATA';
export const PURCHASE_ORDER_CONFIRM_LOADING = 'PURCHASE_ORDER_CONFIRM_LOADING';

// HOD GPS Tracking
export const HOD_GPS_USER_CHANGE = 'HOD_GPS_USER_CHANGE';
export const HOD_GPS_DATE_CHANGE = 'HOD_GPS_DATE_CHANGE';
export const HOD_GPS_DATA_LOADED = 'HOD_GPS_DATA_LOADED';
export const HOD_GPS_USER_LOADED = 'HOD_GPS_USER_LOADED';
export const HOD_GPS_STOP_LOADED = 'HOD_GPS_STOP_LOADED';
export const HOD_GPS_CLEAR = 'HOD_GPS_CLEAR';


// USER TEAM allocation
export const USER_TEAM_LOADED_TEAMS = 'USER_TEAM_LOADED_TEAMS';
export const USER_TEAM_LOADED_USERS = 'USER_TEAM_LOADED_USERS';
export const USER_TEAM_ADD_USERS = 'USER_TEAM_ADD_USERS';
export const USER_TEAM_ADD_TEAMS = 'USER_TEAM_ADD_TEAMS';
export const USER_TEAM_REMOVE_USERS = 'USER_TEAM_REMOVE_USERS';
export const USER_TEAM_REMOVE_TEAMS = 'USER_TEAM_REMOVE_TEAMS';
export const USER_TEAM_CHANGE_TEAM_KEYWORD = 'USER_TEAM_CHANGE_TEAM_KEYWORD';
export const USER_TEAM_CHANGE_USER_KEYWORD = 'USER_TEAM_CHANGE_USER_KEYWORD';
export const USER_TEAM_CLEAR_PAGE = 'USER_TEAM_CLEAR_PAGE';
export const USER_TEAM_LOADED_CHECKED_TEAMS = 'USER_TEAM_LOADED_CHECKED_TEAMS';

// DC Customer Allocation
export const DC_ALLOCATION_CHANGE_DC_USER_NAME = 'DC_ALLOCATION_CHANGE_DC_USER_NAME';
export const DC_ALLOCATION_CHANGE_DC_CHEMIST_NAME = 'DC_ALLOCATION_CHANGE_DC_CHEMIST_NAME';
export const DC_ALLOCATION_USER_LOADED = 'DC_ALLOCATION_USER_LOADED';
export const DC_ALLOCATION_CHEMIST_LOADED = 'DC_ALLOCATION_CHEMIST_LOADED';

export const DC_ALLOCATION_CHANGE_CHECKED_USER = 'DC_ALLOCATION_CHANGE_CHECKED_USER';
export const DC_ALLOCATION_CHANGE_CHECKED_CHEMIST = 'DC_ALLOCATION_CHANGE_CHECKED_CHEMIST';
export const DC_ALLOCATION_APPEND_CHECKED_CHEMIST = 'DC_ALLOCATION_APPEND_CHECKED_CHEMIST';
export const DC_ALLOCATION_CLEAR_PAGE = 'DC_ALLOCATION_CLEAR_PAGE';

// DC_ITINERARY
export const DC_ITINERARY_LOAD = 'DC_ITINERARY_LOAD';
export const DC_ITINERARY_DATE_SELECT = 'DC_ITINERARY_DATE_SELECT';
export const DC_ITINERARY_DAY_TYPE_SELECT = 'DC_ITINERARY_DAY_TYPE_SELECT';
export const DC_ITINERARY_DAY_TYPE_UNSELECT = 'DC_ITINERARY_DAY_TYPE_UNSELECT';
export const DC_ITINERARY_CHANGE_DATE = 'DC_ITINERARY_CHANGE_DATE';
export const DC_ITINERARY_CLEAR_DATE = 'DC_ITINERARY_CLEAR_DATE';
export const DC_ITINERARY_USER_CHANGE = 'DC_ITINERARY_USER_CHANGE';
export const DC_ITINERARY_MODE_CHANGE = 'DC_ITINERARY_MODE_CHANGE';
export const DC_ITINERARY_UPDATING_VALUES_CHANGE = 'DC_ITINERARY_UPDATING_VALUES_CHANGE';
export const DC_ITINERARY_UPDATING_VALUES_CANCEL = 'DC_ITINERARY_UPDATING_VALUES_CANCEL';
export const DC_ITINERARY_AREA_CHANGE = 'DC_ITINERARY_AREA_CHANGE';
export const DC_ITINERARY_TYPE_CHANGE = 'DC_ITINERARY_TYPE_CHANGE';

// INVOICE PAYMENT
export const PAYMENT_INVOICE_NUMBER_CHANGE = 'PAYMENT_INVOICE_NUMBER_CHANGE';
export const PAYMENT_CONFIRM_CLEAR_PAGE = 'PAYMENT_CONFIRM_CLEAR_PAGE';
export const PAYMENT_INVOICE_LOAD_DATA = 'PAYMENT_INVOICE_LOAD_DATA';
export const PAYMENT_INVOICE_CHANGE_DISTRIBUTOR = 'PAYMENT_INVOICE_CHANGE_DISTRIBUTOR';
export const PAYMENT_INVOICE_CHANGE_SALESMAN = 'PAYMENT_INVOICE_CHANGE_SALESMAN';
export const PAYMENT_INVOICE_CHANGE_CUSTOMER = 'PAYMENT_INVOICE_CHANGE_CUSTOMER';
export const PAYMENT_CHECKED_INVOICE = 'PAYMENT_CHECKED_INVOICE';
export const PAYMENT_INVOICE_CHANGE_DATA = 'PAYMENT_INVOICE_CHANGE_DATA';
export const PAYMENT_INVOICE_PAYMENT_AMOUNT_CHANGE = 'PAYMENT_INVOICE_PAYMENT_AMOUNT_CHANGE';
export const PAYMENT_INVOICE_CHANGE_PAYMENT_TYPE = 'PAYMENT_INVOICE_CHANGE_PAYMENT_TYPE';
export const PAYMENT_INVOICE_CHANGE_CHEQUE_DATE = 'PAYMENT_INVOICE_CHANGE_CHEQUE_DATE';
export const PAYMENT_INVOICE_CHANGE_CHEQUE_NO = 'PAYMENT_INVOICE_CHANGE_CHEQUE_NO';
export const PAYMENT_INVOICE_CHANGE_CHEQUE_BANK = 'PAYMENT_INVOICE_CHANGE_CHEQUE_BANK';
export const PAYMENT_INVOICE_CHANGE_CHEQUE_BRANCH = 'PAYMENT_INVOICE_CHANGE_CHEQUE_BRANCH';

// Company Return
export const COMPANY_RETURN_CHANGE_GRN_NUMBER = 'COMPANY_RETURN_CHANGE_GRN_NUMBER';
export const COMPANY_RETURN_LOAD_INFO = 'COMPANY_RETURN_LOAD_INFO';
export const COMPANY_RETURN_CHANGE_QTY = 'COMPANY_RETURN_CHANGE_QTY';
export const COMPANY_RETURN_CHANGE_REASON = 'COMPANY_RETURN_CHANGE_REASON';
export const COMPANY_RETURN_CHANGE_SALLABLE = 'COMPANY_RETURN_CHANGE_SALLABLE';
export const COMPANY_RETURN_CHANGE_REMARK = 'COMPANY_RETURN_CHANGE_REMARK';
export const COMPANY_RETURN_CLEAR_PAGE = 'COMPANY_RETURN_CLEAR_PAGE';

// Competitors
export const COMPETITOR_CHANGE_FROM_DATE = 'COMPETITOR_CHANGE_FROM_DATE';
export const COMPETITOR_CHANGE_TO_DATE = 'COMPETITOR_CHANGE_TO_DATE';
export const COMPETITOR_LOAD_DATA = 'COMPETITOR_LOAD_DATA';
export const COMPETITOR_EDIT_DATA = 'COMPETITOR_LOAD_DATA';
export const COMPETITOR_EDIT_LOAD_DATA = 'COMPETITOR_EDIT_LOAD_DATA';
export const COMPETITOR_CHANGE_EDIT_FROM_DATE = 'COMPETITOR_CHANGE_EDIT_FROM_DATE';
export const COMPETITOR_CHANGE_EDIT_TO_DATE = 'COMPETITOR_CHANGE_EDIT_TO_DATE';

