export const SEARCHING_RECORDS = 'SEARCHING_RECORDS';
export const USER_AREAS_TERRITORY_SEARCH = 'USER_AREAS_TERRITORY_SEARCH';
export const USER_AREAS_USER_SEARCH = 'USER_AREAS_USER_SEARCH';
export const BONUS_FETCH = 'BONUS_FETCH';